services:
  - type: web
    name: donation-site-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn donation_site.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: donation_site_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: donation_site_db
    databaseName: donation_site
    user: donation_site 