services:
  - type: web
    name: donation-site-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn donation_site.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: donation_site_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_LIST_ID
        value: "2"
      - key: GOOGLE_ANALYTICS_ID
        value: "G-EWBWQP7K62"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
    buildFilter:
      paths:
      - requirements.txt
      - "**/*.py"
      - build.sh

databases:
  - name: donation_site_db
    databaseName: donation_site
    user: donation_site 