# Generated by Django 5.1.5 on 2025-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hebrew', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='מילות חיפוש עבור ה-API, מופרדות בפסיקים')),
            ],
            options={
                'verbose_name': 'קטגוריית תרומה',
                'verbose_name_plural': 'קטגוריות תרומה',
            },
        ),
        migrations.CreateModel(
            name='DonationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם המקום')),
                ('address', models.TextField(verbose_name='כתובת')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='טלפון')),
                ('website', models.URLField(blank=True, null=True, verbose_name='אתר אינטרנט')),
                ('opening_hours', models.TextField(blank=True, null=True, verbose_name='שעות פתיחה')),
                ('google_place_id', models.CharField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='עודכן לאחרונה')),
                ('categories', models.ManyToManyField(to='locations.donationcategory', verbose_name='קטגוריות')),
            ],
            options={
                'verbose_name': 'מיקום תרומה',
                'verbose_name_plural': 'מיקומי תרומה',
            },
        ),
    ]
