# Generated by Django 5.1.6 on 2025-02-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_donationlocation_latitude_donationlocation_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationlocation',
            options={},
        ),
    ]
